# Generated by Django 3.2.6 on 2021-08-23 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPwdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sttime', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='a',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, default='Start', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='verify_pin',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttime', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1024)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.chat')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=32)),
                ('groupDP', models.ImageField(blank=True, null=True, upload_to='')),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('chats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.chat')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='msgs',
            field=models.ManyToManyField(blank=True, related_name='listmsgs', to='authentication.msg'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, to='authentication.Friend'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='group_requests',
            field=models.ManyToManyField(blank=True, default=None, to='authentication.Group'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='authentication.Group'),
        ),
    ]
