# Generated by Django 3.2.6 on 2021-11-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userinfo_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_img',
        ),
    ]
