# Generated by Django 3.2.6 on 2021-11-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userinfo_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
